#!/usr/bin/python

import RTC_DS1302
import os
import time
import sys


ds = RTC_DS1302.RTC_DS1302()

if sys.argv[1] == "w":
    t = time.localtime()
    
    ds.WriteDateTime(
        t.tm_year - 2000,
        t.tm_mon,
        t.tm_mday,
        t.tm_wday+1,
        t.tm_hour,
        t.tm_min,
        t.tm_sec)

elif sys.argv[1] == "r":
    dt = { "Year":0, "Month":0, "Day":0, "DayOfWeek":0, "Hour":0, "Minute":0, "Second":0 }
    ds.ReadDateTime(dt)
    cmd = "sudo date %02d%02d%02d%02d20%02d.%02d" % (
            dt["Month"],
            dt["Day"],
            dt["Hour"],
            dt["Minute"],
            dt["Year"],
            dt["Second"]
        )
    os.system(cmd)

else:
    print("Usage: <r|w>")

